defaults:
  - _self_
  - model: RandomForest
  - experiment_tracking: local_server
  - data: nyc_taxi_green
  - metrics:
    - rmse
    - max_error

experiment_tracking:
  enabled: true
  experiment_name: "default-random-forest"

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S} #_${hydra.job.override_dirname}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
